app:
    resource: "@AppBundle/Controller/"
    type:     annotation

miRutaVariableConYaml:
  path: /yml/{miVariable}/
  defaults:
    _controller: 'AppBundle:Default:miRutaVariableConYaml'
  requirements:
    miVariable: test|dev|prod